### ISSUE TITLE
Error:the asset type has not been initialized

### ISSUE THREAD

**Issue by VanHoth** [Lommix/bevy_aseprite_ultra#12]
![image](https://github.com/user-attachments/assets/67f41835-93c9-4f7d-8a63-3b1513165070)

**Comment by VanHoth** [comment]
![image](https://github.com/user-attachments/assets/80515d8b-3203-4340-a2c1-4d72fcf55b01)

**Comment by Lommix** [comment]
You may want to add the `BevySprityPlugin` to your app. Old name, I should rename it to `BevyAsepriteUltraPlugin`

**Comment by VanHoth** [comment]
Thank you so muck!! I did a test and I found that if the aseprite contains groups, it doesn't display.
