### ISSUE TITLE
Modifying an animation's current frame or progress

### ISSUE THREAD

**Issue by lenny991** [Lommix/bevy_aseprite_ultra#14]
Hey, I'll drop this as a question here because I'm having a limitation with this crate. I'd find it very useful for it to be possible to change an animation's current frame, and to be able to easily know the start and end frames, or the length of the animation so that the start frame is always zero. 

This would be great for e.g. air animations (frame depends on velocity) and bow animations (frame depends on load%). I understand that I could do this some other way with maybe slices but it would be great to be able to still use the same component because my player uses the AsepriteAnimationBundle for all of its other animations, and using something else for the air animation would just be a pain in the butt. 

I already forked this crate, thought it'd be an easy fix to just expose the AnimationState struct, but it wasn't that simple. How I'd implement this is with an Event, which one can send to change an animation's current frame (usize) or an animation's progress (from 0.0 to 1.0, the safer method)

Also if there is some way to do this please correct me, maybe I can't just find the right solution. 

Thanks!

**Comment by Lommix** [comment]
The most straight forward way would be to make the values of the `AnimationState` component public. On the `Animation` Component set `playing` to false and manipulate the `current_frame` of the state yourself.

You can access the start and endframe of animation from the aseprite asset. It holds a hashmap of all the meta data of a tag. including start and endframe. Take a look at `animation.rs` line 228-240

**Comment by Lommix** [comment]
Good news, I did not forget.

in the bevy 0.15 release there is now a `ManualTick` Componet. Adding it will prevent the animation system to take over. The Animation State is now public. Animation state logic and render are now seperated.

You can access the asset, read out the start and endframe of any animation tag and change the state according to your logic.
On frame change you must trigger the `FrameChangedEvent` on your sprite (observer) by hand. Else the renderer will not update the current frame.

**Comment by Lommix** [comment]
I am closing this for now, if your requirements are not met, let me know.
