### ISSUE TITLE
Regressions in 0.3.0

### ISSUE THREAD

**Issue by aratama** [Lommix/bevy_aseprite_ultra#15]
Hello,
I'm using this great crate. Thank you so much :)

I found some regressions in version 0.3.0. 
Changing the `name` property of AseSpriteSlice doesn't work. 
I think the query for `update_aseprite_sprite_slice` should be as follows:

```rs
mut nodes: Query<
(Entity, &mut Sprite, &AseSpriteSlice),
Or<(Without<FullyLoaded>, Changed<AseSpriteSlice>)>,
>,
```

The same goes for `update_aseprite_ui_slice`.

Related: #8

It's a different issue, but I had to add the `bevy_winit` and `bevy_window` features to run the example.

**Comment by Lommix** [comment]
Thx for the issue. This is a core function, I consider to have very high prio!
I will investigate and push an update later today.

**Comment by Lommix** [comment]
I implemented your change and added the functionality to the examples (UI & sprites).

You can now `cargo update` to version 0.3.1!

(also made the `dev` features just a dev-dependency. The examples run by default again)

**Comment by aratama** [comment]
@Lommix 

I have confirmed that it works correctly.
Impressively quick work, thank you!
