### ISSUE TITLE
animation::ManualTick is not exported

### ISSUE THREAD

**Issue by Valetoriy** [Lommix/bevy_aseprite_ultra#22]
ManualTick is declared as `pub` and even has an explaining comment attached, but it's not present in crate's `prelude`

**Comment by Valetoriy** [comment]
Also it's not obvious how to use it, so adding an example would be very appreciated

**Comment by Lommix** [comment]
Glad I did. I just tried to make an example, and it feels terrible ... (first frame does even not render).

I'm going to refactor some parts of the animation system and make a `NextFrame` Event.

You will then be able to trigger this on the target entity. I'll try to get it out tomorrow

**Comment by Lommix** [comment]
Good morning!

I made some big changes to the internal workings of the animation system and also added an example on how do manual progress the current selected animation with little to no boilerplate.

**Comment by Valetoriy** [comment]
Thanks a lot!
