### ISSUE TITLE
Is there any ergonomic api for user change there tag?

### ISSUE THREAD

**Issue by darkautism** [Lommix/bevy_aseprite_ultra#3]
For example, I would like my character to have tags such as idle, attack, and die, and be changed by the external system when the game changes.

**Comment by onelson** [comment]
I have also been trying to figure this out 😅 

For my use case, I've got a series of looped tags, and I want to activate one or the other, interrupting the current regardless of how far along into the frame range it is.

I tried a number of approaches, but nothing quite worked. The closest I got was querying for the `Animation` component and setting its `tag` field directly, but doing this end up playing frames from outside the tag's range during the transition.

Not sure what my options are today.

**Comment by Lommix** [comment]
I merged your request and also added a new function 'play' for the animation component, that lets you switch tags more easily.

**Comment by onelson** [comment]
`Animation::play()` is working well for me, thanks 🙏🏻
